#!/usr/bin/env ruby

# frozen_string_literal: true

require_relative 'tweet_storm_generator'

text_to_convert = ARGV.first

if text_to_convert.nil?
  $stdout.puts('Usage: tweetstormgenerator <text>')

  exit(1)
end

begin
  storm = TweetStorms::Generate.call(text_to_convert)

  $stdout.puts(storm.to_thread_string)
rescue WordTooBig => error
  $stdout.puts("Error: #{error.message}")

  exit(1)
end
