version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Configure Bundler
          command: |
            gem install bundler

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Download cc-test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Notify Code Climate about a pending coverage check
          command: ./cc-test-reporter before-build
      - run:
          name: run tests
          command: bundle exec rspec --color --require spec_helper spec --format progress
      - run:
          name: Upload report to Code Climate
          command: |
            ./cc-test-reporter format-coverage -t simplecov tmp/coverage/.resultset.json
            ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID
